package com.example;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "PERSON".
 */
public class Person {

    private Long id;
    /** Not-null value. */
    private String Name;
    /** Not-null value. */
    private String Age;
    private String Address;

    public Person() {
    }

    public Person(Long id) {
        this.id = id;
    }

    public Person(Long id, String Name, String Age, String Address) {
        this.id = id;
        this.Name = Name;
        this.Age = Age;
        this.Address = Address;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /** Not-null value. */
    public String getName() {
        return Name;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setName(String Name) {
        this.Name = Name;
    }

    /** Not-null value. */
    public String getAge() {
        return Age;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setAge(String Age) {
        this.Age = Age;
    }

    public String getAddress() {
        return Address;
    }

    public void setAddress(String Address) {
        this.Address = Address;
    }

}
